/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: this file should normally be auto-generated by `next dev`/`next build`.
// It's committed here so `tsc` and editors work before the first run.
